######################################################################
#
# File name : tb_elaborate.do
# Created on: Sun Feb 12 17:00:00 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\questasim64_10.6c\\win64\\vopt -64 +acc=npr -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -work xil_defaultlib xil_defaultlib.tb xil_defaultlib.glbl -o tb_opt

quit -force
