######################################################################
#
# File name : tb_wave.do
# Created on: Sun Feb 12 16:19:59 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
