# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/FPGA_study/projects/ip_cores/ip_cores.srcs/sources_1/ip/sfifo_8x256/sfifo_8x256.xci
# IP: The module: 'sfifo_8x256' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA_study/projects/ip_cores/ip_cores.srcs/sources_1/ip/sfifo_8x256/sfifo_8x256.xdc
# XDC: The top module name and the constraint reference have the same name: 'sfifo_8x256'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/FPGA_study/projects/ip_cores/ip_cores.srcs/sources_1/ip/sfifo_8x256/sfifo_8x256_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sfifo_8x256'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/FPGA_study/projects/ip_cores/ip_cores.srcs/sources_1/ip/sfifo_8x256/sfifo_8x256_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'sfifo_8x256'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/FPGA_study/projects/ip_cores/ip_cores.srcs/sources_1/ip/sfifo_8x256/sfifo_8x256.xci
# IP: The module: 'sfifo_8x256' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA_study/projects/ip_cores/ip_cores.srcs/sources_1/ip/sfifo_8x256/sfifo_8x256.xdc
# XDC: The top module name and the constraint reference have the same name: 'sfifo_8x256'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/FPGA_study/projects/ip_cores/ip_cores.srcs/sources_1/ip/sfifo_8x256/sfifo_8x256_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sfifo_8x256'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/FPGA_study/projects/ip_cores/ip_cores.srcs/sources_1/ip/sfifo_8x256/sfifo_8x256_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'sfifo_8x256'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
