######################################################################
#
# File name : tb_fifo_compile.do
# Created on: Sun Jan 01 13:10:17 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\questasim64_10.6c\\win64\\vlib questa_lib/work
D:\\questasim64_10.6c\\win64\\vlib questa_lib/msim

D:\\questasim64_10.6c\\win64\\vlib questa_lib/msim/xil_defaultlib

D:\\questasim64_10.6c\\win64\\vmap xil_defaultlib questa_lib/msim/xil_defaultlib

D:\\questasim64_10.6c\\win64\\vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../ip_cores.srcs/sources_1/ip/pll_ip" \
"../../../../ip_cores.ip_user_files/ip/dfifo_1/sim/dfifo_1.v" \
"../../../../ip_cores.srcs/sources_1/new/fifo.v" \

D:\\questasim64_10.6c\\win64\\vlog -64 -incr -sv -work xil_defaultlib  "+incdir+../../../../ip_cores.srcs/sources_1/ip/pll_ip" \
"../../../../ip_cores.srcs/sim_1/new/tb_fifo/rpt_pkg.sv" \
"../../../../ip_cores.srcs/sim_1/new/tb_fifo/access_pkg.sv" \
"../../../../ip_cores.srcs/sim_1/new/tb_fifo/checker_pkg.sv" \
"../../../../ip_cores.srcs/sim_1/new/tb_fifo/test_pkg.sv" \
"../../../../ip_cores.srcs/sim_1/new/tb_fifo/tb_fifo.sv" \

# compile glbl module
D:\\questasim64_10.6c\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

