######################################################################
#
# File name : tb_fifo.udo
# Created on: Mon Dec 26 16:16:43 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
