######################################################################
#
# File name : tb_beep_wave.do
# Created on: Sun Nov 27 15:46:16 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
