######################################################################
#
# File name : tb_beep_compile.do
# Created on: Tue Nov 29 15:24:37 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog -64 -incr -work xil_defaultlib  \
"../../../../0001_project_beep.srcs/sources_1/new/beep.v" \
"../../../../0001_project_beep.srcs/sources_1/new/key_press.v" \
"../../../../0001_project_beep.srcs/sources_1/new/pwm_gen.v" \
"../../../../0001_project_beep.srcs/sim_1/new/tb_beep.v" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

