######################################################################
#
# File name : tb_lcd_display_compile.do
# Created on: Wed Feb 08 15:38:33 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\questasim64_10.6c\\win64\\vlib questa_lib/work
D:\\questasim64_10.6c\\win64\\vlib questa_lib/msim

D:\\questasim64_10.6c\\win64\\vlib questa_lib/msim/xil_defaultlib

D:\\questasim64_10.6c\\win64\\vmap xil_defaultlib questa_lib/msim/xil_defaultlib

D:\\questasim64_10.6c\\win64\\vlog -64 -incr -work xil_defaultlib  \
"../../../../../../src/rtl/display.v" \
"../../../../../../src/rtl/lcd_display.v" \

D:\\questasim64_10.6c\\win64\\vlog -64 -incr -sv -work xil_defaultlib  \
"../../../../../../src/sim/rpt_pkg.sv" \
"../../../../../../src/sim/lcd_pkg.sv" \
"../../../../../../src/sim/tb_lcd_display.sv" \

# compile glbl module
D:\\questasim64_10.6c\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

