######################################################################
#
# File name : tb_lcd_display_elaborate.do
# Created on: Wed Feb 08 15:38:34 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\questasim64_10.6c\\win64\\vopt -64 +acc=npr -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -work xil_defaultlib xil_defaultlib.tb_lcd_display xil_defaultlib.glbl -o tb_lcd_display_opt

quit -force
