######################################################################
#
# File name : tb_lcd_display.udo
# Created on: Sun Feb 05 17:18:12 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
