######################################################################
#
# File name : tb_lcd_display_wave.do
# Created on: Sun Feb 05 17:18:12 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
