######################################################################
#
# File name : tb_compile.do
# Created on: Sun Feb 12 16:59:59 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\questasim64_10.6c\\win64\\vlib questa_lib/work
D:\\questasim64_10.6c\\win64\\vlib questa_lib/msim

D:\\questasim64_10.6c\\win64\\vlib questa_lib/msim/xil_defaultlib

D:\\questasim64_10.6c\\win64\\vmap xil_defaultlib questa_lib/msim/xil_defaultlib

D:\\questasim64_10.6c\\win64\\vlog -64 -incr -work xil_defaultlib  \
"../../../../../../src/rtl/HDMI_top.v" \
"../../../../../../src/rtl/display.v" \
"../../../../../../src/rtl/serializer.v" \
"../../../../../../src/rtl/tmds_encoder.v" \
"../../../../../../src/rtl/top.v" \

D:\\questasim64_10.6c\\win64\\vlog -64 -incr -sv -work xil_defaultlib  \
"../../../../../../src/sim/tb.sv" \

# compile glbl module
D:\\questasim64_10.6c\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

