######################################################################
#
# File name : top_wave.do
# Created on: Sun Feb 12 16:18:44 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
