######################################################################
#
# File name : top_elaborate.do
# Created on: Sun Feb 12 16:18:41 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\questasim64_10.6c\\win64\\vopt -64 +acc=npr -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -work xil_defaultlib xil_defaultlib.top xil_defaultlib.glbl -o top_opt

quit -force
