######################################################################
#
# File name : tb_fifo_wave.do
# Created on: Mon Dec 26 14:46:29 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
