######################################################################
#
# File name : tb_fifo.udo
# Created on: Mon Dec 26 14:46:29 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
