######################################################################
#
# File name : tb_fifo_compile.do
# Created on: Sun Jan 01 13:09:20 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../ip_cores.srcs/sources_1/ip/pll_ip" \
"../../../../ip_cores.ip_user_files/ip/dfifo_1/sim/dfifo_1.v" \
"../../../../ip_cores.srcs/sources_1/new/fifo.v" \

vlog -64 -incr -sv -work xil_defaultlib  "+incdir+../../../../ip_cores.srcs/sources_1/ip/pll_ip" \
"../../../../ip_cores.srcs/sim_1/new/tb_fifo/rpt_pkg.sv" \
"../../../../ip_cores.srcs/sim_1/new/tb_fifo/access_pkg.sv" \
"../../../../ip_cores.srcs/sim_1/new/tb_fifo/checker_pkg.sv" \
"../../../../ip_cores.srcs/sim_1/new/tb_fifo/test_pkg.sv" \
"../../../../ip_cores.srcs/sim_1/new/tb_fifo/tb_fifo.sv" \

# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

