######################################################################
#
# File name : tb_fifo_simulate.do
# Created on: Sun Jan 01 13:09:22 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" +TESTNAME=read_write_test -L fifo_generator_v13_2_3 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm -lib xil_defaultlib xil_defaultlib.tb_fifo xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_fifo_wave.do}

view wave
view structure
view signals

do {tb_fifo.udo}

run 1000ns
