######################################################################
#
# File name : tb_pll_wave.do
# Created on: Mon Dec 26 15:05:58 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
