######################################################################
#
# File name : tb_pll_compile.do
# Created on: Mon Dec 26 15:05:56 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../ip_cores.srcs/sources_1/ip/pll_ip" \
"../../../../ip_cores.srcs/sources_1/ip/pll_ip/pll_ip_clk_wiz.v" \
"../../../../ip_cores.srcs/sources_1/ip/pll_ip/pll_ip.v" \
"../../../../ip_cores.srcs/sources_1/new/pll.v" \
"../../../../ip_cores.srcs/sim_1/new/tb_pll.v" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

