######################################################################
#
# File name : tb_rom_wave.do
# Created on: Sat Dec 03 14:09:12 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
