######################################################################
#
# File name : tb_rom_compile.do
# Created on: Sat Dec 03 14:14:40 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../ip_cores.srcs/sources_1/ip/pll_ip" \
"../../../../ip_cores.srcs/sources_1/ip/rom_8x256/sim/rom_8x256.v" \
"../../../../ip_cores.srcs/sources_1/new/rom.v" \
"../../../../ip_cores.srcs/sim_1/new/tb_rom.v" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

