######################################################################
#
# File name : tb_ram_compile.do
# Created on: Wed Dec 07 14:06:22 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../ip_cores.srcs/sources_1/ip/pll_ip" \
"../../../../ip_cores.srcs/sources_1/ip/s_ram_8x256/sim/s_ram_8x256.v" \
"../../../../ip_cores.srcs/sources_1/new/ram.v" \

vlog -64 -incr -sv -work xil_defaultlib  "+incdir+../../../../ip_cores.srcs/sources_1/ip/pll_ip" \
"../../../../ip_cores.srcs/sim_1/new/tb_ram.sv" \

# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

