######################################################################
#
# File name : tb_ram_wave.do
# Created on: Sat Dec 03 15:22:28 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
